import { applySalesGoldenScenarios } from './sales-golden-scenarios.mjs';
import { applyPurchaseGoldenScenarios } from './purchase-golden-scenarios.mjs';
import { applyProductionQualityGoldenScenarios } from './production-quality-golden-scenarios.mjs';

export function createSeedData() {
  return applyProductionQualityGoldenScenarios(applyPurchaseGoldenScenarios(applySalesGoldenScenarios({
    version: 1,
    updatedAt: new Date().toISOString(),
    masterData: {
      customers: [
        {
          code: 'CUS-00001',
          name: '杭州千层增材科技',
          type: '打印农场',
          contact: '林经理',
          phone: '138-0571-6218',
          email: 'lin@hzqianzeng.example',
          regionType: '国内',
          province: '浙江省',
          city: '杭州市',
          address: '滨江区滨安路 1197 号 3D 打印中心',
          invoiceTitle: '杭州千层增材科技有限公司',
          taxNumber: '91330108MA8AM6218X',
          registeredAddress: '杭州市滨江区滨安路 1197 号 2 幢',
          invoicePhone: '0571-8621-6218',
          bankName: '招商银行杭州滨江支行',
          bankAccount: '5719 0000 0000 6218',
          creditLimit: '300000',
          paymentMethod: '月结',
          paymentTermDays: 30,
          currency: 'CNY',
          deliveryMethod: '送货到厂',
          defaultLogisticsMode: '本厂配送',
          defaultShipContact: '林经理',
          defaultShipPhone: '138-0571-6218',
          defaultShipAddress: '浙江省杭州市余杭区创景路 88 号 A3 仓',
          taxMode: '含税',
          status: '启用',
          updatedAt: '2026-06-17',
          note: '常购 PLA、PETG 标准色耗材；外箱需标注材料、颜色、批次和净重。',
        },
        {
          code: 'CUS-00002',
          name: '苏州维创三维科技',
          type: '贸易商',
          contact: '顾经理',
          phone: '139-0512-6208',
          email: 'gu@szweichuang3d.example',
          regionType: '国内',
          province: '江苏省',
          city: '苏州市',
          address: '工业园区星湖街 328 号',
          invoiceTitle: '苏州维创三维科技有限公司',
          taxNumber: '91320594MA7VC6208Q',
          registeredAddress: '苏州市工业园区星湖街 328 号',
          invoicePhone: '0512-6620-6208',
          bankName: '中国银行苏州工业园区支行',
          bankAccount: '4567 0000 0000 6208',
          creditLimit: '200000',
          paymentMethod: '预付 30%',
          paymentTermDays: 0,
          currency: 'CNY',
          deliveryMethod: '物流发运',
          defaultLogisticsMode: '拼车物流',
          defaultShipContact: '顾经理',
          defaultShipPhone: '139-0512-6208',
          defaultShipAddress: '苏州市工业园区星湖街 328 号 A3 仓',
          taxMode: '含税',
          status: '启用',
          updatedAt: '2026-06-14',
          note: '渠道客户，透明 PETG 和常规色 PLA 按整箱发运。',
        },
        {
          code: 'CUS-00003',
          name: '宁波造物工坊',
          type: '文创工作室',
          contact: '赵老师',
          phone: '137-0574-5306',
          email: 'zhao@nbzaowu.example',
          regionType: '国内',
          province: '浙江省',
          city: '宁波市',
          address: '鄞州区首南街道文创路 88 号',
          invoiceTitle: '宁波造物文化创意有限公司',
          taxNumber: '91330212MA7ZW5306P',
          registeredAddress: '宁波市鄞州区首南街道文创路 88 号',
          invoicePhone: '0574-8853-5306',
          bankName: '宁波银行鄞州支行',
          bankAccount: '3302 0000 0000 5306',
          creditLimit: '0',
          paymentMethod: '款到发货',
          paymentTermDays: 0,
          currency: 'CNY',
          deliveryMethod: '客户自提',
          defaultLogisticsMode: '客户自提',
          defaultShipContact: '赵老师',
          defaultShipPhone: '137-0574-5306',
          defaultShipAddress: '',
          taxMode: '含税',
          status: '停用',
          updatedAt: '2026-06-09',
          note: '历史客户，保留既有业务记录；停用后不再用于新报价和订单。',
        },
      ],
      materials: [
        {
          code: 'M-FG-PETG-175-BLK',
          name: 'PETG 1.75mm 黑色耗材 1kg',
          englishName: 'PETG 1.75mm Black Filament 1kg',
          type: '成品',
          model: 'PETG-175-BLK-1KG',
          spec: '线径 1.75mm，净重 1kg，黑色',
          englishModel: 'PETG-175-BLK-1KG',
          englishSpec: 'Diameter 1.75mm, net weight 1kg, black',
          category: '成品',
          isSaleable: true,
          supplyStrategy: '自制',
          defaultWarehouse: '成品仓',
          purchaseLeadTimeDays: '',
          productionLeadTimeDays: 3,
          safetyStock: 300,
          reorderPoint: 500,
          batchControl: '批次管理',
          shelfLife: '24个月',
          qualityControl: '不适用',
          incomingQualityControl: '不适用',
          inboundQualityControl: '需质检',
          uom: '卷',
          imageLabel: 'PETG',
          imageTone: '#22262b',
          owner: '生产管理部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '标准零售成品，黑色 PETG 线材；成品批次追溯到树脂、色母和挤出流转批次。',
        },
        {
          code: 'M-FG-PLA-175-WHT',
          name: 'PLA 1.75mm 珍珠白耗材 1kg',
          englishName: 'PLA 1.75mm Pearl White Filament 1kg',
          type: '成品',
          model: 'PLA-175-WHT-1KG',
          spec: '线径 1.75mm，净重 1kg，珍珠白',
          englishModel: 'PLA-175-WHT-1KG',
          englishSpec: 'Diameter 1.75mm, net weight 1kg, pearl white',
          category: '成品',
          isSaleable: true,
          supplyStrategy: '自制',
          defaultWarehouse: '成品仓',
          purchaseLeadTimeDays: '',
          productionLeadTimeDays: 3,
          safetyStock: 400,
          reorderPoint: 650,
          batchControl: '批次管理',
          shelfLife: '18个月',
          qualityControl: '不适用',
          incomingQualityControl: '不适用',
          inboundQualityControl: '需质检',
          uom: '卷',
          imageLabel: 'PLA',
          imageTone: '#f0eee7',
          owner: '生产管理部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '标准零售成品，珍珠白 PLA 线材；完工入库前检查线径、净重、绕线与包装。',
        },
        {
          code: 'M-FG-PETG-175-CLR',
          name: 'PETG 1.75mm 透明耗材 1kg',
          type: '成品',
          model: 'PETG-175-CLR-1KG',
          spec: '线径 1.75mm，净重 1kg，透明',
          category: '成品',
          isSaleable: true,
          supplyStrategy: '自制',
          defaultWarehouse: '成品仓',
          purchaseLeadTimeDays: '',
          productionLeadTimeDays: 3,
          safetyStock: 200,
          reorderPoint: 350,
          batchControl: '批次管理',
          shelfLife: '24个月',
          qualityControl: '不适用',
          incomingQualityControl: '不适用',
          inboundQualityControl: '需质检',
          uom: '卷',
          imageLabel: 'CLR',
          imageTone: '#dce7e8',
          owner: '生产管理部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '透明 PETG 零售成品，重点控制晶点、气泡、透光性与线径波动。',
        },
        {
          code: 'M-FG-PLA-175-MBK',
          name: 'PLA 1.75mm 哑光黑耗材 1kg',
          type: '成品',
          model: 'PLA-175-MBK-1KG',
          spec: '线径 1.75mm，净重 1kg，哑光黑',
          category: '成品',
          isSaleable: true,
          supplyStrategy: '自制',
          defaultWarehouse: '成品仓',
          purchaseLeadTimeDays: '',
          productionLeadTimeDays: 3,
          safetyStock: 240,
          reorderPoint: 400,
          batchControl: '批次管理',
          shelfLife: '18个月',
          qualityControl: '不适用',
          incomingQualityControl: '不适用',
          inboundQualityControl: '需质检',
          uom: '卷',
          imageLabel: 'MBK',
          imageTone: '#35383b',
          owner: '生产管理部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '哑光系列零售成品，配方和表面效果需按版本追溯。',
        },
        {
          code: 'M-RM-PETG-VIRGIN',
          name: 'PETG 原生粒子',
          type: '原料',
          model: 'PETG-IV078',
          spec: '挤出级，IV 0.78±0.02',
          category: '原料',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '原料仓',
          purchaseLeadTimeDays: 12,
          productionLeadTimeDays: '',
          safetyStock: 3000,
          reorderPoint: 5000,
          batchControl: '批次管理',
          shelfLife: '24个月',
          qualityControl: '需质检',
          incomingQualityControl: '需质检',
          inboundQualityControl: '不适用',
          uom: 'kg',
          imageLabel: 'PETG',
          imageTone: '#d9e7eb',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: 'PETG 主料，按供应商批号管理；检验水分、熔指、色差和外观。',
        },
        {
          code: 'M-RM-PLA-VIRGIN',
          name: 'PLA 原生粒子',
          type: '原料',
          model: 'PLA-4032D',
          spec: '挤出级，高流动，高透明',
          category: '原料',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '原料仓',
          purchaseLeadTimeDays: 12,
          productionLeadTimeDays: '',
          safetyStock: 4000,
          reorderPoint: 6500,
          batchControl: '批次管理',
          shelfLife: '18个月',
          qualityControl: '需质检',
          incomingQualityControl: '需质检',
          inboundQualityControl: '不适用',
          uom: 'kg',
          imageLabel: 'PLA',
          imageTone: '#e9e7dd',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: 'PLA 主料，重点控制含水率、熔指和颗粒污染，开封后需密封防潮。',
        },
        {
          code: 'M-CM-BLACK',
          name: '黑色色母',
          type: '色母',
          model: 'CM-BLK-01',
          spec: '通用黑，载体适配 PLA/PETG',
          category: '色母',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '原料仓',
          purchaseLeadTimeDays: 10,
          productionLeadTimeDays: '',
          safetyStock: 150,
          reorderPoint: 250,
          batchControl: '批次管理',
          shelfLife: '24个月',
          qualityControl: '需质检',
          incomingQualityControl: '需质检',
          inboundQualityControl: '不适用',
          uom: 'kg',
          imageLabel: 'BLK',
          imageTone: '#202327',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '用于 PETG 黑色及常规黑色线材，按配方比例领用并追踪色差。',
        },
        {
          code: 'M-CM-PEARL-WHT',
          name: '珍珠白色母',
          type: '色母',
          model: 'CM-PWHT-01',
          spec: '珍珠白，PLA 专用',
          category: '色母',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '原料仓',
          purchaseLeadTimeDays: 10,
          productionLeadTimeDays: '',
          safetyStock: 100,
          reorderPoint: 180,
          batchControl: '批次管理',
          shelfLife: '24个月',
          qualityControl: '需质检',
          incomingQualityControl: '需质检',
          inboundQualityControl: '不适用',
          uom: 'kg',
          imageLabel: 'PW',
          imageTone: '#f1efe7',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: 'PLA 珍珠白产品专用色母，按标准样板确认色差。',
        },
        {
          code: 'M-CM-MATTE-BLK',
          name: '哑光黑色母',
          type: '色母',
          model: 'CM-MBLK-01',
          spec: '哑光黑，PLA 专用',
          category: '色母',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '原料仓',
          purchaseLeadTimeDays: 10,
          productionLeadTimeDays: '',
          safetyStock: 100,
          reorderPoint: 180,
          batchControl: '批次管理',
          shelfLife: '24个月',
          qualityControl: '需质检',
          incomingQualityControl: '需质检',
          inboundQualityControl: '不适用',
          uom: 'kg',
          imageLabel: 'MBK',
          imageTone: '#34363a',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '哑光系列专用，色差和表面光泽需同时判定。',
        },
        {
          code: 'M-CM-IND-GRY',
          name: '工业灰色母',
          type: '色母',
          model: 'CM-IGRY-01',
          spec: '中性工业灰，通用型',
          category: '色母',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '原料仓',
          purchaseLeadTimeDays: 10,
          productionLeadTimeDays: '',
          safetyStock: 80,
          reorderPoint: 140,
          batchControl: '批次管理',
          shelfLife: '24个月',
          qualityControl: '需质检',
          incomingQualityControl: '需质检',
          inboundQualityControl: '不适用',
          uom: 'kg',
          imageLabel: 'GRY',
          imageTone: '#7e858a',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '灰色系列配色使用，按批次和标准色板管理。',
        },
        {
          code: 'M-AM-TOUGHENER',
          name: '增韧助剂',
          type: '辅料',
          model: 'ADD-TOUGH-01',
          spec: 'PLA/PETG 挤出级增韧剂',
          category: '辅料',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '原料仓',
          purchaseLeadTimeDays: 12,
          productionLeadTimeDays: '',
          safetyStock: 120,
          reorderPoint: 200,
          batchControl: '批次管理',
          shelfLife: '18个月',
          qualityControl: '需质检',
          incomingQualityControl: '需质检',
          inboundQualityControl: '不适用',
          uom: 'kg',
          imageLabel: 'TGH',
          imageTone: '#d9e2d1',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '按配方比例投入，需追踪批号和有效期。',
        },
        {
          code: 'M-AM-CLEAR-ENH',
          name: '透明增强助剂',
          type: '辅料',
          model: 'ADD-CLEAR-01',
          spec: 'PETG 透明度与流动性改善',
          category: '辅料',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '原料仓',
          purchaseLeadTimeDays: 12,
          productionLeadTimeDays: '',
          safetyStock: 80,
          reorderPoint: 140,
          batchControl: '批次管理',
          shelfLife: '18个月',
          qualityControl: '需质检',
          incomingQualityControl: '需质检',
          inboundQualityControl: '不适用',
          uom: 'kg',
          imageLabel: 'CLR+',
          imageTone: '#e6efee',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '透明 PETG 配方专用，需按配方版本限量使用。',
        },
        {
          code: 'M-AM-DESICCANT',
          name: '干燥剂 5g',
          type: '辅料',
          model: 'DES-5G',
          spec: '5g/包，食品级硅胶',
          category: '辅料',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '包材仓',
          purchaseLeadTimeDays: 7,
          productionLeadTimeDays: '',
          safetyStock: 5000,
          reorderPoint: 8000,
          batchControl: '批次管理',
          shelfLife: '24个月',
          qualityControl: '免检',
          incomingQualityControl: '免检',
          inboundQualityControl: '不适用',
          uom: '个',
          imageLabel: '5g',
          imageTone: '#e8e3d8',
          owner: '仓储中心',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '每卷真空包装使用 1 包，按供应批次管理。',
        },
        {
          code: 'M-PKG-SPOOL-1KG',
          name: '小盘线轴 1kg',
          type: '包材',
          model: 'SPOOL-1KG',
          spec: '外径 200mm，黑色可回收线盘',
          category: '包材',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '包材仓',
          purchaseLeadTimeDays: 10,
          productionLeadTimeDays: '',
          safetyStock: 3000,
          reorderPoint: 5000,
          batchControl: '批次管理',
          shelfLife: '无效期要求',
          qualityControl: '抽检',
          incomingQualityControl: '抽检',
          inboundQualityControl: '不适用',
          uom: '个',
          imageLabel: '1KG',
          imageTone: '#32363a',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '1kg 零售线材收卷使用，检验尺寸、毛刺和变形。',
        },
        {
          code: 'M-PKG-VAC-BAG-1KG',
          name: '真空包装袋 1kg',
          type: '包材',
          model: 'VAC-BAG-1KG',
          spec: '尼龙复合袋，适配 1kg 线盘',
          category: '包材',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '包材仓',
          purchaseLeadTimeDays: 8,
          productionLeadTimeDays: '',
          safetyStock: 4000,
          reorderPoint: 6500,
          batchControl: '批次管理',
          shelfLife: '无效期要求',
          qualityControl: '抽检',
          incomingQualityControl: '抽检',
          inboundQualityControl: '不适用',
          uom: '个',
          imageLabel: 'VAC',
          imageTone: '#dce2e4',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '成品防潮包装，来料抽检封口强度和漏气。',
        },
        {
          code: 'M-PKG-COLORBOX-1KG',
          name: '零售彩盒 1kg',
          type: '包材',
          model: 'BOX-COLOR-1KG',
          spec: '通用品牌彩盒，适配 1kg 线盘',
          category: '包材',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '包材仓',
          purchaseLeadTimeDays: 12,
          productionLeadTimeDays: '',
          safetyStock: 3000,
          reorderPoint: 5000,
          batchControl: '批次管理',
          shelfLife: '无效期要求',
          qualityControl: '抽检',
          incomingQualityControl: '抽检',
          inboundQualityControl: '不适用',
          uom: '个',
          imageLabel: 'BOX',
          imageTone: '#e8ddc8',
          owner: '采购部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '零售包装使用，检验印刷版本、色差、压痕和条码区域。',
        },
        {
          code: 'M-PKG-CARTON-12',
          name: '外箱 12卷装',
          type: '包材',
          model: 'CARTON-12R',
          spec: '五层瓦楞，12 卷/箱',
          category: '包材',
          isSaleable: false,
          supplyStrategy: '采购',
          defaultWarehouse: '包材仓',
          purchaseLeadTimeDays: 10,
          productionLeadTimeDays: '',
          safetyStock: 300,
          reorderPoint: 500,
          batchControl: '不追踪批次',
          shelfLife: '无效期要求',
          qualityControl: '免检',
          incomingQualityControl: '免检',
          inboundQualityControl: '不适用',
          uom: '个',
          imageLabel: '12R',
          imageTone: '#cdb998',
          owner: '仓储中心',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '销售出库装箱使用，默认 12 卷一箱。',
        },
        {
          code: 'M-RG-PLA-A',
          name: 'PLA 一级回料',
          type: '回料',
          model: 'PLA-RG-A',
          spec: '清洁单色回料，已粉碎',
          category: '回料',
          isSaleable: false,
          supplyStrategy: '自制',
          defaultWarehouse: '回料与不良品区',
          purchaseLeadTimeDays: '',
          productionLeadTimeDays: '',
          safetyStock: 0,
          reorderPoint: 0,
          batchControl: '批次管理',
          shelfLife: '3个月',
          qualityControl: '不适用',
          incomingQualityControl: '不适用',
          inboundQualityControl: '需质检',
          uom: 'kg',
          imageLabel: 'RG-A',
          imageTone: '#b9c8aa',
          owner: '生产管理部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '生产过程产生的清洁 PLA 回料，复用前需按批次评估掺用比例。',
        },
        {
          code: 'M-DF-FILAMENT-MIX',
          name: '不良丝材待处理',
          type: '不良品',
          model: 'DEF-FIL-MIX',
          spec: '断丝、超差、混色线材',
          category: '不良品',
          isSaleable: false,
          supplyStrategy: '自制',
          defaultWarehouse: '回料与不良品区',
          purchaseLeadTimeDays: '',
          productionLeadTimeDays: '',
          safetyStock: 0,
          reorderPoint: 0,
          batchControl: '批次管理',
          shelfLife: '无效期要求',
          qualityControl: '不适用',
          incomingQualityControl: '不适用',
          inboundQualityControl: '需质检',
          uom: 'kg',
          imageLabel: 'NG',
          imageTone: '#b85e58',
          owner: '质量部',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '隔离存放，质量判定后转回料、返工或报废，不参与可用库存。',
        },
      ],
      warehouses: [
        {
          code: 'WH-FG',
          name: '成品仓',
          type: '成品仓',
          company: 'Filatrix 增材材料有限公司',
          regionType: '国内',
          province: '浙江省',
          city: '杭州市',
          address: '滨江区江南大道 1688 号 1 号仓库',
          locationCount: 18,
          binPrefix: 'FG',
          warehouseFunctions: ['可销售出库', '可生产入库'],
          allowPurchaseReceipt: false,
          allowSalesIssue: true,
          allowProductionIssue: false,
          allowProductionReceipt: true,
          allowQualityHold: false,
          allowQuarantine: false,
          primary: '库位 FG-01 至 FG-18',
          secondary: '默认按批次先进先出',
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 1,
          note: '合格成品存放区，销售发货按批次和先进先出规则拣货。',
        },
        {
          code: 'WH-RM',
          name: '原料仓',
          type: '原料仓',
          company: 'Filatrix 增材材料有限公司',
          regionType: '国内',
          province: '浙江省',
          city: '杭州市',
          address: '滨江区江南大道 1688 号 2 号仓库',
          locationCount: 24,
          binPrefix: 'RM',
          warehouseFunctions: ['可采购入库', '可生产领料'],
          allowPurchaseReceipt: true,
          allowSalesIssue: false,
          allowProductionIssue: true,
          allowProductionReceipt: false,
          allowQualityHold: false,
          allowQuarantine: false,
          primary: '库位 RM-01 至 RM-24',
          secondary: '按材料类别和批次分区',
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 0,
          note: '仅接收检验放行后的原料，采购到货先进入采购暂存区。',
        },
        {
          code: 'WH-PKG',
          name: '包材仓',
          type: '包材仓',
          company: 'Filatrix 增材材料有限公司',
          regionType: '国内',
          province: '浙江省',
          city: '杭州市',
          address: '滨江区江南大道 1688 号 3 号仓库',
          locationCount: 16,
          binPrefix: 'PKG',
          warehouseFunctions: ['可采购入库', '可生产领料'],
          allowPurchaseReceipt: true,
          allowSalesIssue: false,
          allowProductionIssue: true,
          allowProductionReceipt: false,
          allowQualityHold: false,
          allowQuarantine: false,
          primary: '库位 PKG-01 至 PKG-16',
          secondary: '按包装版本与规格分区',
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 0,
          note: '包材与树脂分仓存放，按包装版本和规格管理。',
        },
        {
          code: 'WH-QC-HOLD',
          name: '采购暂存区',
          type: '暂存仓',
          company: 'Filatrix 增材材料有限公司',
          regionType: '国内',
          province: '浙江省',
          city: '杭州市',
          address: '滨江区江南大道 1688 号 2 号仓采购暂存区',
          locationCount: 6,
          binPrefix: 'QC',
          warehouseFunctions: ['采购暂存'],
          allowPurchaseStaging: true,
          allowPurchaseReceipt: false,
          allowSalesIssue: false,
          allowProductionIssue: false,
          allowProductionReceipt: false,
          allowQualityHold: true,
          allowQuarantine: false,
          primary: '6 个可用库位',
          secondary: '采购到货按现场库位暂存，不参与可承诺库存',
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 0,
          note: '采购到货时由仓库选择实际暂存库位；需检物料质检放行、免检物料确认到货后，再转正式入库。',
        },
        {
          code: 'WH-RECYCLE',
          name: '回料与不良品区',
          type: '隔离仓',
          company: 'Filatrix 增材材料有限公司',
          regionType: '国内',
          province: '浙江省',
          city: '杭州市',
          address: '滨江区江南大道 1688 号生产车间隔离区',
          locationCount: 10,
          binPrefix: 'RG',
          warehouseFunctions: ['不合格隔离'],
          allowPurchaseReceipt: false,
          allowSalesIssue: false,
          allowProductionIssue: false,
          allowProductionReceipt: false,
          allowQualityHold: false,
          allowQuarantine: true,
          primary: '库位 RG-01 至 RG-10',
          secondary: '不参与正常可用库存',
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 0,
          note: '质量判定后才允许转回料、返工或报废。',
        },
        {
          code: 'WH-SA-RETURN',
          name: '销售退货暂存区',
          type: '暂存仓',
          company: 'Filatrix 增材材料有限公司',
          regionType: '国内',
          province: '浙江省',
          city: '杭州市',
          address: '滨江区江南大道 1688 号 2 号仓售后区',
          locationCount: 6,
          binPrefix: 'AS',
          warehouseFunctions: ['销售退货暂存'],
          allowPurchaseStaging: false,
          allowSalesReturnStaging: true,
          allowPurchaseReceipt: false,
          allowSalesIssue: false,
          allowProductionIssue: false,
          allowProductionReceipt: false,
          allowQualityHold: false,
          allowQuarantine: false,
          primary: '库位 AS-01 至 AS-06',
          secondary: '客户退回待检，不参与可销售库存',
          status: '启用',
          updatedAt: '2026-07-27',
          attachments: 0,
          note: '客户退回实物先暂存，质检判定后再转可售、返修或报废。',
        },
      ],
      suppliers: [
        {
          code: 'SUP-JXJC',
          name: '嘉兴聚材高分子',
          type: '树脂原料供应商',
          contact: '李经理',
          phone: '136-0000-7108',
          email: 'li@jxjucai.example',
          regionType: '国内',
          province: '浙江省',
          city: '嘉兴市',
          address: '南湖区新材料产业园 199 号',
          invoiceTitle: '嘉兴聚材高分子材料有限公司',
          taxNumber: '91330402MA2JC0001K',
          registeredAddress: '嘉兴市南湖区新材料产业园 199 号',
          invoicePhone: '0573-8710-7108',
          bankName: '招商银行嘉兴分行',
          bankAccount: '3304 0000 0000 7108',
          paymentMethod: '月结',
          paymentTermDays: 30,
          currency: 'CNY',
          taxRate: '13%',
          deliveryMethod: '送货到厂',
          status: '启用',
          updatedAt: '2026-07-16',
          note: 'PLA、PETG 原生树脂的主要供应来源，按厂家批号和质保报告验收。',
        },
        {
          code: 'SUP-SZCS',
          name: '苏州彩塑科技',
          type: '色母助剂供应商',
          contact: '王经理',
          phone: '139-0000-8126',
          email: 'wang@szcaisu.example',
          regionType: '国内',
          province: '江苏省',
          city: '苏州市',
          address: '吴中区化工新材料园金枫南路 88 号',
          invoiceTitle: '苏州彩塑科技有限公司',
          taxNumber: '91320506MA2CS0002M',
          registeredAddress: '苏州市吴中区化工新材料园金枫南路 88 号',
          invoicePhone: '0512-6812-8126',
          bankName: '苏州银行吴中支行',
          bankAccount: '3205 0000 0000 8126',
          paymentMethod: '月结',
          paymentTermDays: 45,
          currency: 'CNY',
          taxRate: '13%',
          deliveryMethod: '快递快运',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '色母、增韧剂和透明增强助剂供应商，按标准色板和样品封样验收。',
        },
        {
          code: 'SUP-HZBZ',
          name: '杭州博展包装',
          type: '包材供应商',
          contact: '周经理',
          phone: '137-0000-9260',
          email: 'zhou@hzbozhan.example',
          regionType: '国内',
          province: '浙江省',
          city: '杭州市',
          address: '余杭区良渚街道通运街 56 号',
          invoiceTitle: '杭州博展包装有限公司',
          taxNumber: '91330110MA2BZ0003R',
          registeredAddress: '杭州市余杭区良渚街道通运街 56 号',
          invoicePhone: '0571-8926-9260',
          bankName: '杭州银行余杭支行',
          bankAccount: '3301 0000 0000 9260',
          paymentMethod: '月结',
          paymentTermDays: 30,
          currency: 'CNY',
          taxRate: '13%',
          deliveryMethod: '本厂配送',
          status: '启用',
          updatedAt: '2026-07-16',
          note: '线盘、真空袋、彩盒、纸箱和干燥剂供应商。',
        },
        {
          code: 'SUP-NBCM',
          name: '宁波彩美新材料',
          type: '色母助剂供应商',
          contact: '沈经理',
          phone: '136-0000-5832',
          email: 'shen@nbcaimei.example',
          regionType: '国内',
          province: '浙江省',
          city: '宁波市',
          address: '北仑区新材料产业园海明路 36 号',
          invoiceTitle: '宁波彩美新材料有限公司',
          taxNumber: '91330206MA2CM5832X',
          registeredAddress: '宁波市北仑区新材料产业园海明路 36 号',
          invoicePhone: '0574-8583-2000',
          bankName: '宁波银行北仑支行',
          bankAccount: '3302 0000 0000 5832',
          paymentMethod: '月结',
          paymentTermDays: 30,
          currency: 'CNY',
          taxRate: '13%',
          deliveryMethod: '送货到厂',
          status: '启用',
          updatedAt: '2026-08-06',
          note: '色母和功能助剂备选供应商，用于交期和起订量比较。',
        },
        {
          code: 'SUP-HZRB',
          name: '杭州锐标智能装备',
          type: '设备供应商',
          contact: '许经理',
          phone: '135-0000-7418',
          email: 'xu@hzruibiao.example',
          regionType: '国内',
          province: '浙江省',
          city: '杭州市',
          address: '萧山区机器人小镇启迪路 28 号',
          invoiceTitle: '杭州锐标智能装备有限公司',
          taxNumber: '91330109MA2RB7418X',
          registeredAddress: '杭州市萧山区机器人小镇启迪路 28 号',
          invoicePhone: '0571-8741-8000',
          bankName: '杭州银行萧山支行',
          bankAccount: '3301 0000 0000 7418',
          paymentMethod: '验收后付款',
          paymentTermDays: 7,
          currency: 'CNY',
          taxRate: '13%',
          deliveryMethod: '供应商送货安装',
          status: '启用',
          updatedAt: '2026-07-18',
          note: '自动贴标、条码校验和包装线集成设备供应商。',
        },
      ],
      uom: [
        {
          code: 'UOM-ROLL',
          name: '卷',
          englishAbbreviation: 'roll',
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 0,
          note: '用于 1kg 成品线材的库存、销售和生产入库。',
        },
        {
          code: 'UOM-KG',
          name: 'kg',
          englishAbbreviation: 'kg',
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 0,
          note: '重量型原料的基础单位。',
        },
        {
          code: 'UOM-G',
          name: 'g',
          englishAbbreviation: 'g',
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 0,
          note: '用于以 g 作为基础单位的小剂量物料；系统不自动换算为 kg。',
        },
        {
          code: 'UOM-EA',
          name: '个',
          englishAbbreviation: 'pcs',
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 0,
          note: '独立包材和辅料的库存基础单位。',
        },
        {
          code: 'UOM-CTN',
          name: '箱',
          englishAbbreviation: 'ctn',
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 0,
          note: '业务数量统一使用物料基础单位；装箱数量由包装物料、包装规则或单据要求维护。',
        },
      ],
      currencies: [
        {
          code: 'CNY',
          name: '人民币',
          symbol: '¥',
          decimalPlaces: 2,
          status: '启用',
          updatedAt: '2026-07-25',
          attachments: 0,
          note: '中国境内默认结算币种。',
        },
      ],
      departments: [
        {
          code: 'DEP-SALES',
          name: '销售管理部',
          parentDepartment: '',
          employeeCount: 1,
          owner: 'Filatrix 增材材料有限公司',
          status: '启用',
          updatedAt: '2026-06-17',
          attachments: 0,
          note: '影响用户所属部门和销售业务范围。',
        },
        {
          code: 'DEP-OPS',
          name: '运营管理部',
          parentDepartment: '',
          employeeCount: 1,
          owner: 'Filatrix 增材材料有限公司',
          status: '启用',
          updatedAt: '2026-06-17',
          attachments: 0,
          note: '系统默认运营部门。',
        },
        {
          code: 'DEP-PUR',
          name: '采购部',
          parentDepartment: '',
          employeeCount: 1,
          owner: 'Filatrix 增材材料有限公司',
          status: '启用',
          updatedAt: '2026-06-16',
          attachments: 0,
          note: '采购模块常用部门。',
        },
        {
          code: 'DEP-WH',
          name: '仓储中心',
          parentDepartment: '',
          employeeCount: 1,
          owner: 'Filatrix 增材材料有限公司',
          status: '启用',
          updatedAt: '2026-06-15',
          attachments: 0,
          note: '发货追踪流转到仓库后由该部门处理。',
        },
        {
          code: 'DEP-FIN',
          name: '财务部',
          parentDepartment: '',
          employeeCount: 1,
          owner: 'Filatrix 增材材料有限公司',
          status: '启用',
          updatedAt: '2026-06-14',
          attachments: 0,
          note: '财务单据与结算处理部门。',
        },
        {
          code: 'DEP-PROD', name: '生产管理部', parentDepartment: '', employeeCount: 1,
          owner: 'Filatrix 增材材料有限公司', status: '启用',
          updatedAt: '2026-07-16', attachments: 0, note: '管理挤出、绕线和包装生产资源。',
        },
        {
          code: 'DEP-QA', name: '质量部', parentDepartment: '', employeeCount: 1,
          owner: 'Filatrix 增材材料有限公司', status: '启用',
          updatedAt: '2026-07-16', attachments: 0, note: '独立承担放行、隔离和不合格处置判定。',
        },
        {
          code: 'DEP-RD', name: '研发部', parentDepartment: '', employeeCount: 1,
          owner: 'Filatrix 增材材料有限公司', status: '启用',
          updatedAt: '2026-07-16', attachments: 0, note: '管理试验产线和配方版本。',
        },
        {
          code: 'DEP-HR', name: '人事行政部', parentDepartment: '', employeeCount: 0,
          owner: 'Filatrix 增材材料有限公司', status: '启用',
          updatedAt: '2026-07-16', attachments: 0, note: '负责人事档案、行政与组织资料维护。',
        },
      ],
      employees: [
        {
          code: 'EMP-ZS',
          name: '张三',
          englishName: 'Zhang San',
          position: '运营负责人',
          linkedAccount: 'zhangsan',
          owner: '运营管理部',
          phone: '138-0000-0001',
          email: 'zhangsan@filatrix.example',
          gender: '男',
          hireDate: '2024-03-01',
          status: '启用',
          updatedAt: '2026-06-17',
          attachments: 1,
          note: '系统管理员账号资料。',
        },
        {
          code: 'EMP-LM',
          name: '李明',
          englishName: 'Li Ming',
          position: '销售主管', linkedAccount: '',
          owner: '销售管理部',
          phone: '138-0000-0002',
          email: 'liming@filatrix.example',
          gender: '男', hireDate: '2024-05-10',
          status: '启用',
          updatedAt: '2026-06-15',
          attachments: 0,
          note: '用于销售业务单据。',
        },
        {
          code: 'EMP-WQ',
          name: '王倩',
          englishName: 'Wang Qian',
          position: '仓库主管', linkedAccount: '',
          owner: '仓储中心',
          phone: '138-0000-0003',
          email: 'wangqian@filatrix.example',
          gender: '女', hireDate: '2024-06-15',
          status: '启用',
          updatedAt: '2026-06-13',
          attachments: 0,
          note: '负责仓库受理和出库确认。',
        },
        {
          code: 'EMP-CC',
          name: '陈晨',
          position: '采购主管', linkedAccount: '',
          owner: '采购部',
          phone: '138-0000-0004',
          email: 'chenchen@filatrix.example',
          gender: '女', hireDate: '2024-07-01',
          status: '启用',
          updatedAt: '2026-06-17',
          attachments: 0,
          note: '用于采购业务单据。',
        },
        {
          code: 'EMP-ZM',
          name: '赵敏',
          englishName: 'Zhao Min',
          position: '财务主管', linkedAccount: '',
          owner: '财务部',
          phone: '138-0000-0005',
          email: 'zhaomin@filatrix.example',
          gender: '女', hireDate: '2024-04-12',
          status: '启用',
          updatedAt: '2026-06-17',
          attachments: 0,
          note: '用于财务业务单据。',
        },
        {
          code: 'EMP-ZN', name: '周宁', englishName: 'Zhou Ning', position: '生产主管', linkedAccount: '',
          owner: '生产管理部', phone: '138-0000-0006',
          email: 'zhouning@filatrix.example', gender: '男', hireDate: '2024-08-05', status: '启用', updatedAt: '2026-07-16',
          attachments: 0, note: '负责挤出、绕线和包装现场协调。',
        },
        {
          code: 'EMP-LS', name: '林珊', englishName: 'Lin Shan', position: '质量主管', linkedAccount: '',
          owner: '质量部', phone: '138-0000-0007',
          email: 'linshan@filatrix.example', gender: '女', hireDate: '2024-09-16', status: '启用', updatedAt: '2026-07-16',
          attachments: 0, note: '负责原料、过程和成品质量判定。',
        },
        {
          code: 'EMP-ZY', name: '赵云', englishName: 'Zhao Yun', position: '材料工艺工程师', linkedAccount: '',
          owner: '研发部', phone: '138-0000-0008',
          email: 'zhaoyun@filatrix.example', gender: '男', hireDate: '2025-01-08', status: '启用', updatedAt: '2026-07-16',
          attachments: 0, note: '负责配方验证、工艺窗口和新品试制。',
        },
      ],
      company: [
        {
          code: 'COM-FILATRIX',
          name: 'Filatrix 增材材料有限公司',
          englishName: 'Filatrix Additive Materials Co., Ltd.',
          type: '总公司',
          primary: 'Filatrix',
          secondary: '13%',
          phone: '0571-0000-6001',
          email: 'ops@filatrix.example',
          website: 'https://www.filatrix.com',
          address: '浙江省杭州市滨江区江南大道 1688 号',
          englishAddress: 'No. 1688 Jiangnan Avenue, Binjiang District, Hangzhou, Zhejiang, China',
          invoiceTitle: 'Filatrix 增材材料有限公司',
          taxNumber: '91330108MA2FILAXXX',
          registeredAddress: '浙江省杭州市滨江区江南大道 1688 号',
          invoicePhone: '0571-0000-6001',
          bankName: '招商银行杭州滨江支行',
          bankAccount: '5719 0000 0000 6001',
          seal: 1,
          status: '启用',
          updatedAt: '2026-07-16',
          attachments: 2,
          note: '当前默认经营主体，用于单据抬头、开票和结算。',
        },
      ],
      equipment: [
        {
          code: 'EQ-DRY-01', name: '树脂除湿干燥机 01', brand: '信易', model: 'SHD-100U',
          spec: '料斗容量 100kg，露点 ≤ -40℃', serialNumber: 'SHD100-250901', primary: '挤出一车间原料准备区',
          owner: '生产管理部', startDate: '2025-09-01', status: '启用', updatedAt: '2026-07-16',
          attachments: 1, note: 'PLA/PETG 投料前除湿干燥，每周清理过滤器。',
        },
        {
          code: 'EQ-EXT-01', name: '单螺杆耗材挤出机 01', brand: '金纬', model: 'JWS45',
          spec: '螺杆直径 45mm，设计产能 50kg/h', serialNumber: 'JWS45-250602', primary: '挤出一车间 1 号线',
          owner: '生产管理部', startDate: '2025-06-02', status: '启用', updatedAt: '2026-07-16',
          attachments: 2, note: '用于 PLA 标准产品挤出，换料时按清机规范执行。',
        },
        {
          code: 'EQ-DIA-01', name: '在线激光测径仪 01', brand: 'Zumbach', model: 'ODAC 18XY',
          spec: '测量范围 0.15-18mm，双轴测量', serialNumber: 'ODAC18-250721', primary: '挤出一车间 1 号线测径段',
          owner: '质量部', startDate: '2025-07-21', status: '启用', updatedAt: '2026-07-16',
          attachments: 1, note: '用于在线测径；镜头清洁和标准棒校验由后续维护单记录。',
        },
        {
          code: 'EQ-MFI-01', name: '熔体流动速率仪 01', brand: '承德金建', model: 'XNR-400B',
          spec: '温度范围 120-450℃', serialNumber: 'XNR400-241108', primary: '质量实验室',
          owner: '质量部', startDate: '2024-11-08', status: '启用', updatedAt: '2026-07-16',
          attachments: 1, note: '用于树脂来料与配方样品熔指检测。',
        },
        {
          code: 'EQ-WIND-01', name: '双工位自动收卷机 01', brand: 'Filatrix 工程', model: 'FW-2S',
          spec: '双工位，适配 1kg 线盘', serialNumber: 'FW2S-251015', primary: '挤出一车间 1 号线收卷段',
          owner: '生产管理部', startDate: '2025-10-15', status: '启用', updatedAt: '2026-07-16',
          attachments: 1, note: '重点检查排线机构、张力和计米轮。',
        },
      ],
      productionLines: [
        {
          code: 'LINE-PLA-01', name: 'PLA 一号挤出线', type: '挤出产线', workshop: '挤出一车间',
          capacityValue: 42, capacityUnit: 'kg/小时', processScope: 'PLA 1.75mm 标准与哑光系列',
          owner: '生产管理部', status: '启用', updatedAt: '2026-07-16',
          attachments: 0, note: '常态生产 PLA 白色、黑色与哑光系列。',
        },
        {
          code: 'LINE-PETG-01', name: 'PETG 二号挤出线', type: '挤出产线', workshop: '挤出一车间',
          capacityValue: 38, capacityUnit: 'kg/小时', processScope: 'PETG 1.75mm 黑色与透明系列',
          owner: '生产管理部', status: '启用', updatedAt: '2026-07-16',
          attachments: 0, note: '配置独立干燥和透明料清机规范。',
        },
        {
          code: 'LINE-REWIND-01', name: '一号复绕线', type: '复绕产线', workshop: '复绕车间',
          capacityValue: 360, capacityUnit: '卷/班', processScope: '大盘半成品复绕为 1kg 小盘成品',
          owner: '生产管理部', status: '启用', updatedAt: '2026-07-22',
          attachments: 0, note: '承接挤出大盘半成品，按来源大盘净重和成品卷数报工。',
        },
        {
          code: 'LINE-RD-01', name: '研发试验挤出线', type: '试验产线', workshop: '研发试制区',
          capacityValue: 8, capacityUnit: 'kg/小时', processScope: '新品配方、小批试制与工艺窗口验证',
          owner: '研发部', status: '启用', updatedAt: '2026-07-16',
          attachments: 1, note: '用于新品配方、小批试制与工艺窗口验证。',
        },
        {
          code: 'LINE-PACK-01', name: '自动包装线 01', type: '包装产线', workshop: '包装车间',
          capacityValue: 220, capacityUnit: '卷/班', processScope: '1kg 线盘真空、装盒、装箱与贴标',
          owner: '生产管理部', status: '启用', updatedAt: '2026-07-16',
          attachments: 0, note: '标准班次产能按 8 小时计算。',
        },
      ],
    },
    masterRelations: {
      materialSuppliers: [
        { code: 'MSR-00001', supplierCode: 'SUP-JXJC', supplierName: '嘉兴聚材高分子', materialCode: 'M-RM-PETG-VIRGIN', materialName: 'PETG 原生粒子', supplierMaterialCode: 'PETG-IV078', minOrderQty: 1000, leadTimeDays: 12, isDefault: true, status: '启用', note: '主供 PETG 原生树脂，按厂家批号和质保报告验收。' },
        { code: 'MSR-00002', supplierCode: 'SUP-JXJC', supplierName: '嘉兴聚材高分子', materialCode: 'M-RM-PLA-VIRGIN', materialName: 'PLA 原生粒子', supplierMaterialCode: 'PLA-4032D', minOrderQty: 1000, leadTimeDays: 12, isDefault: true, status: '启用', note: '主供 PLA 原生树脂，按厂家批号管理。' },
        { code: 'MSR-00003', supplierCode: 'SUP-SZCS', supplierName: '苏州彩塑科技', materialCode: 'M-CM-BLACK', materialName: '黑色色母', supplierMaterialCode: 'CM-BLK-01', minOrderQty: 50, leadTimeDays: 10, isDefault: true, status: '启用' },
        { code: 'MSR-00004', supplierCode: 'SUP-SZCS', supplierName: '苏州彩塑科技', materialCode: 'M-CM-PEARL-WHT', materialName: '珍珠白色母', supplierMaterialCode: 'CM-PWHT-01', minOrderQty: 50, leadTimeDays: 12, isDefault: true, status: '启用' },
        { code: 'MSR-00005', supplierCode: 'SUP-SZCS', supplierName: '苏州彩塑科技', materialCode: 'M-CM-MATTE-BLK', materialName: '哑光黑色母', supplierMaterialCode: 'CM-MBLK-01', minOrderQty: 50, leadTimeDays: 12, isDefault: true, status: '启用' },
        { code: 'MSR-00006', supplierCode: 'SUP-SZCS', supplierName: '苏州彩塑科技', materialCode: 'M-CM-IND-GRY', materialName: '工业灰色母', supplierMaterialCode: 'CM-IGRY-01', minOrderQty: 50, leadTimeDays: 10, isDefault: true, status: '启用' },
        { code: 'MSR-00007', supplierCode: 'SUP-SZCS', supplierName: '苏州彩塑科技', materialCode: 'M-AM-TOUGHENER', materialName: '增韧助剂', supplierMaterialCode: 'ADD-TOUGH-01', minOrderQty: 25, leadTimeDays: 12, isDefault: true, status: '启用' },
        { code: 'MSR-00008', supplierCode: 'SUP-SZCS', supplierName: '苏州彩塑科技', materialCode: 'M-AM-CLEAR-ENH', materialName: '透明增强助剂', supplierMaterialCode: 'ADD-CLEAR-01', minOrderQty: 25, leadTimeDays: 12, isDefault: true, status: '启用' },
        { code: 'MSR-00009', supplierCode: 'SUP-HZBZ', supplierName: '杭州博展包装', materialCode: 'M-AM-DESICCANT', materialName: '干燥剂 5g', supplierMaterialCode: 'DES-5G', minOrderQty: 5000, leadTimeDays: 7, isDefault: true, status: '启用' },
        { code: 'MSR-00010', supplierCode: 'SUP-HZBZ', supplierName: '杭州博展包装', materialCode: 'M-PKG-SPOOL-1KG', materialName: '小盘线轴 1kg', supplierMaterialCode: 'SPOOL-1KG', minOrderQty: 3000, leadTimeDays: 10, isDefault: true, status: '启用' },
        { code: 'MSR-00011', supplierCode: 'SUP-HZBZ', supplierName: '杭州博展包装', materialCode: 'M-PKG-VAC-BAG-1KG', materialName: '真空包装袋 1kg', supplierMaterialCode: 'VAC-BAG-1KG', minOrderQty: 5000, leadTimeDays: 8, isDefault: true, status: '启用' },
        { code: 'MSR-00012', supplierCode: 'SUP-HZBZ', supplierName: '杭州博展包装', materialCode: 'M-PKG-COLORBOX-1KG', materialName: '零售彩盒 1kg', supplierMaterialCode: 'BOX-COLOR-1KG', minOrderQty: 3000, leadTimeDays: 12, isDefault: true, status: '启用' },
        { code: 'MSR-00013', supplierCode: 'SUP-HZBZ', supplierName: '杭州博展包装', materialCode: 'M-PKG-CARTON-12', materialName: '外箱 12卷装', supplierMaterialCode: 'CARTON-12R', minOrderQty: 500, leadTimeDays: 10, isDefault: true, status: '启用' },
        { code: 'MSR-00014', supplierCode: 'SUP-NBCM', supplierName: '宁波彩美新材料', materialCode: 'M-CM-MATTE-BLK', materialName: '哑光黑色母', supplierMaterialCode: 'NB-MBK-02', minOrderQty: 25, leadTimeDays: 15, isDefault: false, status: '启用', note: '哑光黑色母备选供应关系，用于供应风险和交期比较。' },
      ],
      warehouseMaterials: [
        { code: 'WMR-00001', warehouseCode: 'WH-FG', warehouseName: '成品仓', materialCode: 'M-FG-PETG-175-BLK', materialName: 'PETG 1.75mm 黑色耗材 1kg', uom: '卷', safetyStock: 300, reorderPoint: 500, maxStock: 1000, replenishmentLot: 120, status: '启用' },
        { code: 'WMR-00002', warehouseCode: 'WH-FG', warehouseName: '成品仓', materialCode: 'M-FG-PLA-175-WHT', materialName: 'PLA 1.75mm 珍珠白耗材 1kg', uom: '卷', safetyStock: 400, reorderPoint: 650, maxStock: 1300, replenishmentLot: 120, status: '启用' },
        { code: 'WMR-00003', warehouseCode: 'WH-FG', warehouseName: '成品仓', materialCode: 'M-FG-PETG-175-CLR', materialName: 'PETG 1.75mm 透明耗材 1kg', uom: '卷', safetyStock: 200, reorderPoint: 350, maxStock: 700, replenishmentLot: 120, status: '启用' },
        { code: 'WMR-00004', warehouseCode: 'WH-FG', warehouseName: '成品仓', materialCode: 'M-FG-PLA-175-MBK', materialName: 'PLA 1.75mm 哑光黑耗材 1kg', uom: '卷', safetyStock: 240, reorderPoint: 400, maxStock: 800, replenishmentLot: 120, status: '启用' },
        { code: 'WMR-00005', warehouseCode: 'WH-RM', warehouseName: '原料仓', materialCode: 'M-RM-PETG-VIRGIN', materialName: 'PETG 原生粒子', uom: 'kg', safetyStock: 3000, reorderPoint: 5000, maxStock: 10000, replenishmentLot: 2000, status: '启用' },
        { code: 'WMR-00006', warehouseCode: 'WH-RM', warehouseName: '原料仓', materialCode: 'M-RM-PLA-VIRGIN', materialName: 'PLA 原生粒子', uom: 'kg', safetyStock: 4000, reorderPoint: 6500, maxStock: 13000, replenishmentLot: 2000, status: '启用' },
        { code: 'WMR-00007', warehouseCode: 'WH-RM', warehouseName: '原料仓', materialCode: 'M-CM-BLACK', materialName: '黑色色母', uom: 'kg', safetyStock: 150, reorderPoint: 250, maxStock: 500, replenishmentLot: 100, status: '启用' },
        { code: 'WMR-00008', warehouseCode: 'WH-RM', warehouseName: '原料仓', materialCode: 'M-CM-PEARL-WHT', materialName: '珍珠白色母', uom: 'kg', safetyStock: 100, reorderPoint: 180, maxStock: 360, replenishmentLot: 50, status: '启用' },
        { code: 'WMR-00009', warehouseCode: 'WH-RM', warehouseName: '原料仓', materialCode: 'M-CM-MATTE-BLK', materialName: '哑光黑色母', uom: 'kg', safetyStock: 100, reorderPoint: 180, maxStock: 360, replenishmentLot: 50, status: '启用' },
        { code: 'WMR-00010', warehouseCode: 'WH-RM', warehouseName: '原料仓', materialCode: 'M-CM-IND-GRY', materialName: '工业灰色母', uom: 'kg', safetyStock: 80, reorderPoint: 140, maxStock: 280, replenishmentLot: 50, status: '启用' },
        { code: 'WMR-00011', warehouseCode: 'WH-RM', warehouseName: '原料仓', materialCode: 'M-AM-TOUGHENER', materialName: '增韧助剂', uom: 'kg', safetyStock: 120, reorderPoint: 200, maxStock: 400, replenishmentLot: 50, status: '启用' },
        { code: 'WMR-00012', warehouseCode: 'WH-RM', warehouseName: '原料仓', materialCode: 'M-AM-CLEAR-ENH', materialName: '透明增强助剂', uom: 'kg', safetyStock: 80, reorderPoint: 140, maxStock: 280, replenishmentLot: 50, status: '启用' },
        { code: 'WMR-00013', warehouseCode: 'WH-PKG', warehouseName: '包材仓', materialCode: 'M-AM-DESICCANT', materialName: '干燥剂 5g', uom: '个', safetyStock: 5000, reorderPoint: 8000, maxStock: 16000, replenishmentLot: 5000, status: '启用' },
        { code: 'WMR-00014', warehouseCode: 'WH-PKG', warehouseName: '包材仓', materialCode: 'M-PKG-SPOOL-1KG', materialName: '小盘线轴 1kg', uom: '个', safetyStock: 3000, reorderPoint: 5000, maxStock: 10000, replenishmentLot: 3000, status: '启用' },
        { code: 'WMR-00015', warehouseCode: 'WH-PKG', warehouseName: '包材仓', materialCode: 'M-PKG-VAC-BAG-1KG', materialName: '真空包装袋 1kg', uom: '个', safetyStock: 4000, reorderPoint: 6500, maxStock: 13000, replenishmentLot: 5000, status: '启用' },
        { code: 'WMR-00016', warehouseCode: 'WH-PKG', warehouseName: '包材仓', materialCode: 'M-PKG-COLORBOX-1KG', materialName: '零售彩盒 1kg', uom: '个', safetyStock: 3000, reorderPoint: 5000, maxStock: 10000, replenishmentLot: 3000, status: '启用' },
        { code: 'WMR-00017', warehouseCode: 'WH-PKG', warehouseName: '包材仓', materialCode: 'M-PKG-CARTON-12', materialName: '外箱 12卷装', uom: '个', safetyStock: 300, reorderPoint: 500, maxStock: 1000, replenishmentLot: 500, status: '启用' },
      ],
    },
    sales: {
      quotes: [
        {
          code: 'QT-20260721-006',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          customer: '苏州维创三维科技',
          customerCode: 'CUS-00002',
          contact: '顾经理',
          contactPhone: '139-0512-8036',
          products: [{ materialCode: 'M-FG-PLA-175-MBK', name: 'PLA 1.75mm 哑光黑耗材 1kg', qty: '80 卷', unitPrice: '75.00', amount: '￥6,000.00', taxRate: '13%' }],
          amount: '￥6,000.00',
          owner: '李明',
          status: '草稿',
          date: '2026-07-21',
          validUntil: '2026-07-31',
          deliveryMethod: '整车货运',
          freightPayer: '客户',
          paymentMethod: '预付款 30%',
          taxMode: '含税',
          taxRate: '13%',
          remark: '待客户确认哑光黑色样与交付日期。',
          attachments: [],
        },
        {
          code: 'QT-20260720-005',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          customer: '杭州千层增材科技',
          customerCode: 'CUS-00001',
          contact: '林经理',
          contactPhone: '138-0571-6218',
          products: [{ materialCode: 'M-FG-PLA-175-WHT', name: 'PLA 1.75mm 珍珠白耗材 1kg', qty: '100 卷', unitPrice: '74.00', amount: '￥7,400.00', taxRate: '13%' }],
          amount: '￥7,400.00',
          owner: '李明',
          status: '已确认',
          date: '2026-07-20',
          validUntil: '2026-07-30',
          deliveryMethod: '本厂配送',
          freightPayer: '供方',
          paymentMethod: '月结 30 天',
          taxMode: '含税',
          taxRate: '13%',
          remark: '客户已确认标准珍珠白色号和报价，待转销售订单。',
          attachments: [],
        },
        {
          code: 'QT-20260617-004',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          customer: '杭州千层增材科技',
          customerCode: 'CUS-00001',
          contact: '林经理',
          contactPhone: '138-0571-6218',
          products: [
            { materialCode: 'M-FG-PLA-175-WHT', name: 'PLA 1.75mm 珍珠白耗材 1kg', qty: '240 卷', unitPrice: '72.00', amount: '￥17,280.00', taxRate: '13%' },
            { materialCode: 'M-FG-PETG-175-BLK', name: 'PETG 1.75mm 黑色耗材 1kg', qty: '120 卷', unitPrice: '82.00', amount: '￥9,840.00', taxRate: '13%' },
          ],
          amount: '￥27,120.00',
          owner: '李明',
          status: '已转订单',
          convertedOrderCode: 'SO-20260617-021',
          date: '2026-06-17',
          validUntil: '2026-06-24',
          deliveryMethod: '本厂配送',
          freightPayer: '供方',
          paymentMethod: '月结 30 天',
          taxMode: '含税',
          taxRate: '13%',
          remark: '交付至客户杭州仓库，外箱标注色号、生产批次和净重。',
          attachments: [
            { name: '客户确认报价单-QT20260617.pdf', size: '640 KB', uploader: '李明', date: '2026-06-17' },
          ],
        },
        {
          code: 'QT-20260616-019',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          customer: '苏州维创三维科技',
          customerCode: 'CUS-00002',
          contact: '顾经理',
          contactPhone: '139-0512-8036',
          products: [{ materialCode: 'M-FG-PETG-175-CLR', name: 'PETG 1.75mm 透明耗材 1kg', qty: '300 卷', unitPrice: '85.00', amount: '￥25,500.00', taxRate: '13%' }],
          amount: '￥25,500.00',
          owner: '周宁',
          status: '已转订单',
          convertedOrderCode: 'SO-20260715-022',
          date: '2026-06-16',
          validUntil: '2026-06-23',
          deliveryMethod: '整车货运',
          freightPayer: '客户',
          paymentMethod: '预付款 30%',
          taxMode: '含税',
          taxRate: '13%',
          remark: '透明 PETG 成品按 12 卷/箱包装，发货前确认外箱唛头。',
          attachments: [],
        },
      ],
      orders: [
        {
          code: 'SO-20260617-021',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          customerCode: 'CUS-00001',
          customer: '杭州千层增材科技',
          contact: '林经理',
          contactPhone: '138-0571-6218',
          sourceQuote: 'QT-20260617-004',
          products: [
            { lineId: 'L1', materialCode: 'M-FG-PLA-175-WHT', name: 'PLA 1.75mm 珍珠白耗材 1kg', qty: '240 卷', unitPrice: '72.00', amount: '￥17,280.00', uom: '卷', imageLabel: 'PLA', imageTone: '#f0eee7' },
            { lineId: 'L2', materialCode: 'M-FG-PETG-175-BLK', name: 'PETG 1.75mm 黑色耗材 1kg', qty: '120 卷', unitPrice: '82.00', amount: '￥9,840.00', uom: '卷', imageLabel: 'PETG', imageTone: '#22262b' },
          ],
          amount: '￥27,120.00',
          owner: '李明',
          priority: '加急',
          documentStatus: '已确认',
          status: '待发货',
          date: '2026-06-17',
          delivery: '2026-06-24',
          deliveryMethod: '送货到厂',
          freightPayer: '供方',
          paymentMethod: '月结 30 天',
          taxMode: '含税',
          taxRate: '13%',
          logisticsMode: '本厂配送',
          plannedShipDate: '2026-06-22',
          shipAddress: '浙江省杭州市余杭区创景路 88 号 A3 仓',
          shipContact: '林经理',
          shipPhone: '138-0571-6218',
          internalRemark: '按客户采购订单分两种物料复核，外箱分别标注 PLA 珍珠白与 PETG 黑色。',
          productionProgress: { status: '无需生产', plannedQty: 0, completedQty: 0 },
          deliveryProgress: { status: '待分配', orderedQty: 360, outboundQty: 0, signedQty: 0 },
          invoiceProgress: { status: '未开票', orderAmount: 27120, invoicedAmount: 0 },
          paymentProgress: { status: '未收款', receivableAmount: 0, settledAmount: 0 },
          attentionFlags: { status: '交付逾期' },
          remark: '按客户确认的报价单执行，出库前复核色号、生产批次、净重和包装标签。',
          attachments: [
            { name: '杭州千层增材科技-盖章销售合同.pdf', size: '1.8 MB', uploader: '李明', date: '2026-06-17' },
            { name: '客户采购订单-PO20260617.pdf', size: '860 KB', uploader: '李明', date: '2026-06-17' },
          ],
        },
        {
          code: 'SO-20260528-008',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          customerCode: 'CUS-00002',
          customer: '苏州维创三维科技',
          contact: '顾经理',
          contactPhone: '139-0512-8036',
          sourceQuote: '',
          products: [
            { lineId: 'L1', materialCode: 'M-FG-PLA-175-MBK', name: 'PLA 1.75mm 哑光黑耗材 1kg', qty: '180 卷', unitPrice: '69.00', amount: '￥12,420.00', uom: '卷', imageLabel: 'PLA', imageTone: '#25272a' },
          ],
          amount: '￥12,420.00',
          owner: '周宁',
          priority: '正常',
          documentStatus: '已关闭',
          status: '已完成',
          date: '2026-05-28',
          delivery: '2026-06-02',
          deliveryMethod: '送货到厂',
          freightPayer: '供方',
          paymentMethod: '月结 30 天',
          taxMode: '含税',
          taxRate: '13%',
          logisticsMode: '本厂配送',
          plannedShipDate: '2026-06-01',
          shipAddress: '江苏省苏州市吴中区兴创路 26 号 2 号仓',
          shipContact: '顾经理',
          shipPhone: '139-0512-8036',
          internalRemark: '按 12 卷/箱装箱，外箱使用客户定制标签。',
          productionProgress: { status: '无需生产', plannedQty: 0, completedQty: 0 },
          deliveryProgress: { status: '已签收', orderedQty: 180, outboundQty: 180, signedQty: 180 },
          invoiceProgress: { status: '已开票', orderAmount: 12420, invoicedAmount: 12420 },
          paymentProgress: { status: '已收款', receivableAmount: 12420, settledAmount: 12420 },
          attentionFlags: { status: '正常' },
          remark: '已按客户要求交付并完成签收、开票和收款。',
          attachments: [
            { name: 'SO-20260528-008-客户签收单.pdf', size: '720 KB', uploader: '周宁', date: '2026-06-02' },
          ],
        },
      ],
      quoteFlowRecords: {
        'QT-20260721-006': [
          { time: '2026-07-21 15:20', actor: '李明', action: '保存报价', remark: '报价保存为草稿，等待客户确认色样与交期。' },
        ],
        'QT-20260720-005': [
          { time: '2026-07-20 10:10', actor: '李明', action: '保存报价', remark: '录入客户、销售物料、价格和商务条款。' },
          { time: '2026-07-20 11:35', actor: '李明', action: '确认报价', remark: '客户确认价格、色号和商务条件。' },
        ],
        'QT-20260617-004': [
          { time: '2026-06-17 09:18', actor: '李明', action: '保存报价', remark: '录入客户、销售物料、价格和商务条款。' },
          { time: '2026-06-17 10:42', actor: '李明', action: '确认报价', remark: '客户确认价格和商务条件。' },
          { time: '2026-06-17 10:50', actor: '李明', action: '转销售订单', remark: 'SO-20260617-021 已由该报价生成。' },
        ],
        'QT-20260616-019': [
          { time: '2026-06-16 16:20', actor: '周宁', action: '保存报价', remark: '报价保存为草稿，等待客户确认。' },
          { time: '2026-06-17 09:05', actor: '周宁', action: '确认报价', remark: '客户确认价格、数量和商务条件。' },
          { time: '2026-07-15 08:55', actor: '周宁', action: '转销售订单', remark: 'SO-20260715-022 已由该报价生成。' },
        ],
      },
      orderFlowRecords: {
        'SO-20260617-021': [
          { time: '2026-06-17 10:55', actor: '李明', action: '确认订单', remark: '由报价单 QT-20260617-004 转入并确认销售订单。' },
          { time: '2026-06-17 11:08', actor: '李明', action: '上传附件', remark: '上传盖章销售合同与客户采购订单。' },
        ],
        'SO-20260528-008': [
          { time: '2026-05-28 14:10', actor: '周宁', action: '确认订单', remark: '客户确认哑光黑 PLA 成品和定制标签要求。' },
          { time: '2026-06-02 16:25', actor: '周宁', action: '确认签收', remark: '客户已签收 180 卷成品。' },
          { time: '2026-06-30 10:15', actor: '系统', action: '关闭订单', remark: '交付、开票和收款均已完成。' },
        ],
      },
      outboundRequests: [
        {
          code: 'SR-20260617-001',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          sourceOrder: 'SO-20260617-021',
          customerCode: 'CUS-00001',
          customer: '杭州千层增材科技',
          contact: '林经理',
          contactPhone: '138-0571-6218',
          products: [
            { sourceLineId: 'L1', materialCode: 'M-FG-PLA-175-WHT', name: 'PLA 1.75mm 珍珠白耗材 1kg', qty: '240 卷', requestQty: '240 卷', uom: '卷' },
            { sourceLineId: 'L2', materialCode: 'M-FG-PETG-175-BLK', name: 'PETG 1.75mm 黑色耗材 1kg', qty: '120 卷', requestQty: '120 卷', uom: '卷' },
          ],
          applicant: '李明',
          status: '待发货',
          requestDate: '2026-06-17',
          expectedDate: '2026-06-22',
          deliveryDate: '2026-06-24',
          deliveryMethod: '本厂配送',
          warehouseCode: 'WH-FG',
          warehouse: '成品仓',
          address: '浙江省杭州市余杭区创景路 88 号 A3 仓',
          remark: '销售已确认发货要求，等待仓库按订单预留批次拣货。',
          attachments: [],
        },
        {
          code: 'SR-20260601-002',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          sourceOrder: 'SO-20260528-008',
          customerCode: 'CUS-00002',
          customer: '苏州维创三维科技',
          contact: '顾经理',
          contactPhone: '139-0512-8036',
          products: [
            { sourceLineId: 'L1', materialCode: 'M-FG-PLA-175-MBK', name: 'PLA 1.75mm 哑光黑耗材 1kg', qty: '180 卷', requestQty: '180 卷', uom: '卷' },
          ],
          applicant: '周宁',
          status: '已签收',
          requestDate: '2026-05-28',
          expectedDate: '2026-06-01',
          deliveryDate: '2026-06-02',
          deliveryMethod: '本厂配送',
          warehouseCode: 'WH-FG',
          warehouse: '成品仓',
          address: '江苏省苏州市吴中区兴创路 26 号 2 号仓',
          signedAt: '2026-06-02 16:25',
          signedBy: '周宁',
          remark: '已完成出库并由客户签收。',
          attachments: [],
        },
      ],
      outboundRequestFlowRecords: {
        'SR-20260617-001': [
          { time: '2026-06-17 10:56', actor: '系统', action: '生成交付追踪', remark: 'SO-20260617-021 确认后自动生成交付追踪。' },
          { time: '2026-06-17 11:02', actor: '李明', action: '确认发货要求', remark: '确认收货信息、计划发货日期和成品仓。' },
        ],
        'SR-20260601-002': [
          { time: '2026-05-28 14:12', actor: '系统', action: '生成交付追踪', remark: 'SO-20260528-008 确认后生成交付追踪。' },
          { time: '2026-06-01 15:40', actor: '仓库主管', action: '已出库', remark: 'WS-20260601-003 已完成 180 卷成品出库。' },
          { time: '2026-06-02 16:25', actor: '周宁', action: '确认客户签收', remark: '客户已签收本次交付。' },
        ],
      },
      afterSales: [
        {
          code: 'SA-20260605-001',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          sourceOrder: 'SO-20260528-008',
          customerCode: 'CUS-00002',
          customer: '苏州维创三维科技',
          contact: '顾经理',
          contactPhone: '139-0512-8036',
          issueType: '包装/标签',
          issueDescription: '客户反馈其中 12 卷外箱标签粘贴位置不统一，产品本体与数量无异常。',
          action: '补发',
          responsibility: '仓库补寄，销售跟进签收',
          amountImpact: '无',
          processingResult: '',
          confirmationNote: '',
          owner: '周宁',
          status: '处理中',
          nextStep: '确认补寄标签签收',
          date: '2026-06-05',
          sourceStatus: '已关闭',
          sourceAmount: '￥12,420.00',
          sourceDate: '2026-05-28',
          sourceDueDate: '2026-06-02',
          sourceRemark: '已按客户要求交付并完成签收、开票和收款。',
          products: [
            { sourceLineId: 'L1', materialCode: 'M-FG-PLA-175-MBK', name: 'PLA 1.75mm 哑光黑耗材 1kg', qty: '12 卷', sourceQty: '180 卷', uom: '卷' },
          ],
          attachments: [
            { name: '客户标签反馈照片.zip', size: '3.4 MB', uploader: '周宁', date: '2026-06-05' },
          ],
        },
      ],
      afterSalesFlowRecords: {
        'SA-20260605-001': [
          { time: '2026-06-05 09:30', actor: '周宁', action: '登记销售售后', remark: '客户反馈其中两箱外箱标签粘贴位置不统一。' },
          { time: '2026-06-05 10:20', actor: '周宁', action: '受理售后', remark: '已安排仓库补寄标签并发送粘贴位置示意。' },
        ],
      },
    },
    warehouse: {
      salesIssues: [
        {
          code: 'WS-20260601-003',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          sourceDoc: 'SR-20260601-002',
          sourceOrder: 'SO-20260528-008',
          customerCode: 'CUS-00002',
          customer: '苏州维创三维科技',
          contact: '顾经理',
          contactPhone: '139-0512-8036',
          products: [
            { sourceLineId: 'L1', materialCode: 'M-FG-PLA-175-MBK', name: 'PLA 1.75mm 哑光黑耗材 1kg', qty: '180 卷', batch: 'PLA-MBK-260526-A', uom: '卷' },
          ],
          warehouseCode: 'WH-FG',
          warehouse: '成品仓',
          deliveryMethod: '本厂配送',
          owner: '仓库主管',
          status: '已出库',
          date: '2026-06-01',
          expectedDate: '2026-06-01',
          note: '按客户定制标签要求复核后出库。',
        },
      ],
      salesIssueFlowRecords: {
        'WS-20260601-003': [
          { time: '2026-06-01 14:50', actor: '仓库主管', action: '受理出库', remark: '承接交付追踪 SR-20260601-002。' },
          { time: '2026-06-01 15:40', actor: '仓库主管', action: '确认出库', remark: '180 卷成品完成复核并出库。' },
        ],
      },
    },
    finance: {
      salesInvoices: [
        {
          code: 'SI-20260603-002',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          sourceDoc: 'SO-20260528-008',
          sourceOrder: 'SO-20260528-008',
          partyCode: 'CUS-00002',
          party: '苏州维创三维科技',
          contact: '顾经理',
          contactPhone: '139-0512-8036',
          amount: '￥10,991.15',
          taxAmount: '￥1,428.85',
          totalAmount: '￥12,420.00',
          settledAmount: '￥12,420.00',
          owner: '赵敏',
          status: '已收款',
          date: '2026-06-03',
          dueDate: '2026-07-03',
          invoiceType: '增值税专用发票',
          paymentMethod: '月结 30 天',
          bankAccount: '',
          lines: [
            { lineId: 'L1', sourceOrder: 'SO-20260528-008', sourceLineId: 'L1', materialCode: 'M-FG-PLA-175-MBK', name: 'PLA 1.75mm 哑光黑耗材 1kg', qty: '180 卷', unitPrice: '69.00', amount: '￥12,420.00', taxRate: '13%', uom: '卷' },
          ],
          note: '销售订单全额开票。',
        },
      ],
      receivables: [
        {
          code: 'AR-20260603-002',
          companyCode: 'COM-FILATRIX',
          company: 'Filatrix 增材材料有限公司',
          sourceDoc: 'SI-20260603-002',
          sourceOrder: 'SO-20260528-008',
          partyCode: 'CUS-00002',
          party: '苏州维创三维科技',
          contact: '顾经理',
          contactPhone: '139-0512-8036',
          amount: '￥10,991.15',
          taxAmount: '￥1,428.85',
          totalAmount: '￥12,420.00',
          settledAmount: '￥12,420.00',
          owner: '赵敏',
          status: '已收款',
          date: '2026-06-03',
          dueDate: '2026-07-03',
          invoiceType: '应收账款',
          paymentMethod: '月结 30 天',
          bankAccount: '',
          lines: [
            { lineId: 'L1', sourceOrder: 'SO-20260528-008', sourceLineId: 'L1', materialCode: 'M-FG-PLA-175-MBK', name: 'PLA 1.75mm 哑光黑耗材 1kg', qty: '180 卷', unitPrice: '69.00', amount: '￥12,420.00', taxRate: '13%', uom: '卷' },
          ],
          note: '由销售发票 SI-20260603-002 生成并已完成收款核销。',
        },
      ],
      receivablePayments: {
        'AR-20260603-002': [
          { code: 'RCV-20260630-001', receivableCode: 'AR-20260603-002', sourceOrder: 'SO-20260528-008', amount: 12420, date: '2026-06-30', method: '银行转账', actor: '赵敏', idempotencyKey: 'seed-so-20260528-008-payment', createdAt: '2026-06-30 10:05' },
        ],
      },
      salesInvoiceFlowRecords: {
        'SI-20260603-002': [
          { time: '2026-06-03 10:20', actor: '赵敏', action: '确认销售发票', remark: '销售订单 SO-20260528-008 已全额开票。' },
        ],
      },
      receivableFlowRecords: {
        'AR-20260603-002': [
          { time: '2026-06-03 10:20', actor: '系统', action: '生成应收账款', remark: '由销售发票 SI-20260603-002 自动生成。' },
          { time: '2026-06-30 10:05', actor: '赵敏', action: '登记收款', remark: '本次收款 ￥12,420.00，累计已全额收款。' },
        ],
      },
    },
  })));
}
